### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by Wintus** [Wintus/Ansible-WSL#1]
# TODOs
- [x] add supports of other OS
  - non GNU/Linux (e.g. BSD) maybe supported: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-machine-requirements
  - pywinrm
https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows
- [x] extract roles
  - refer another ubuntu project: https://github.com/Wintus/ansible-local
  - bash.d role
  - just delete it #8 

## docs
- [x] official guide: https://docs.ansible.com/ansible/latest/user_guide/windows.html
- [ ] make the concept clear (adding diagrams?)
  - PlantUML?: http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

## distros

other than [Ubuntu](https://www.microsoft.com/ja-jp/p/ubuntu-1804-lts/9n9tngvndl3q)

- [ ] suse
- [ ] WLinux

## refs
- https://qiita.com/yunano/items/f9d5652a296931a09a70

**Comment by Wintus** [comment]
> * add supports of other OS

WSL = Windows Subsystem for Linux;
Thus, Linux is the only option.

Consider distros.

**Comment by Wintus** [comment]
Extracted
